### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by Lucky8Young** [phdsky/ORBSLAM24Windows#1]
Thanks for your great work!
I manage to compile everything in the README.md but I don't know how to run some applications.Because I didn't compile and run a ubuntu project on windows with visual studio.
Could you please tell me how to do it or give me some advices about it in details?
Thank you very much?

**Comment by phdsky** [comment]
Hello Lucky8Young!
If you want to make apps, you can also build the mono-stero-RGBD projects provided.
Take mono_tum app as an example, you can follow the steps below.  
1. Go to the ORBSLAM24Windows/build folder, double click the ORB_SLAM2.sln to open the peoject.
2. Choose either debug or release mode you want. **(Build mode should be the same as DBoW2 && g2o && Pangolin && ORB_SLAM2)**.
3. Right click the mono_tum project and then click generate.
4. Download tum dataset sequence, for example [freiburg2_desk ](http://filecremers3.informatik.tu-muenchen.de/rgbd/dataset/freiburg2/rgbd_dataset_freiburg2_desk.tgz)
5. Right click the mono_tum project and then click Property->Config Property->Debug, input three parameters (Usage: ./mono_tum path_to_vocabulary path_to_settings path_to_sequence, the first can be ignored in windows)
 - **path_to_vocabulary**  In ORBSLAM24Windows/Vocabulary folder, unpack the tar, a .txt file
 - **path_to_settings**  In ORBSLAM24Windows/Examples/Monocular folder, rgbd_dataset_freiburg2_desk corresponding to TUM2.yaml
 - **path_to_sequence** rgbd_dataset_freiburg2_desk folder path
6. Run app, it'll take a few minutes to load the vocabulary dictionary, and then you'll get the result.

If you don't satisfied with the speed of loading dictionary, you can reference issue [vocabulary convert](https://github.com/raulmur/ORB_SLAM2/pull/21) to convert the txt vocabulary  to bin vocabulary, it speeds up a lot.

**Comment by Lucky8Young** [comment]
Thanks for your help! I'm very sorry for the late reply.
I followed your advice and it worked but the effect wasn't very good. Maybe there were some mistakes I mad that need to be re corrected.
