### ISSUE TITLE
ORB SLAM2.lib unable to open

### ISSUE THREAD

**Issue by bombrake** [phdsky/ORBSLAM24Windows#2]
I'm using Opencv 3.2 on windows 10 with VS 2015.
Everything builds fine except for the main ORBSLAM2 library.
The error that Visual Studio throws is:
LINK : fatal error LNK1181: cannot open input file '..\lib\Release\ORB_SLAM2.lib'

The above directory is empty.
Any ideas on how to solve this issue?

Thanks!

**Comment by bombrake** [comment]
Issue Solved:
The library was not being generated due to ORBExtractor.cpp throwing an error.
Adding #include <iterator> to the .cpp file solved the build error.

**Comment by carlosfarinhas** [comment]
@hari0920 were did you add the #include, and what did you included?
