### ISSUE TITLE
C2039 'back_inserter': is not a member of 'std'

### ISSUE THREAD

**Issue by komori556** [phdsky/ORBSLAM24Windows#3]
Tried to build ORB_SLAM2  with Visual Studio 2015 , but ALL_BUILD of ORB_SLAM2.sln  got an error in line 450 of ORBextractor.cc:
Error C2039: 'back_inserter': is not a member of 'std'
Error C3861: 'back_inserter': identifier not found

ORBextractor.cc need "iterator" with Visual Studio 2015(vc14).
```
#include <iterator>
```
I use opencv 3.2.0 and visual studio 2015(vc14). This project work correctly.

**Comment by devphilno** [comment]
Thanks for the Comment helped me out as well
