### ISSUE TITLE
Difficulty at building "Application"

### ISSUE THREAD

**Issue by donald2016** [phdsky/ORBSLAM24Windows#5]
I am trying to build the example of mono_tum; however, I am not understand the following steps.

> Right click the mono_tum project and then click generate.
Download tum dataset sequence, for example freiburg2_desk
Right click the mono_tum project and then click Property->Config Property->Debug, input three parameters (Usage: ./mono_tum path_to_vocabulary path_to_settings path_to_sequence, the first can be ignored in windows)

I am using Visual Studio Express 2015, I do not have the option "generate" when I right click mono_tum project. Is it the same as "Build" ?
Moreover, I cannot find "Property->Config Property->Debug". Are there any corresponding location for setup.

Thanks for your help. This source is very helpful.

Side track suggestion: When I build "ORB_Slam2" I met the error "back_inserter': is not a member of 'std". I have added #include <iterator> to that folder to complete the build

**Comment by phdsky** [comment]
Hi, donald2016
I'm using vs2013 not 15, so I don't know the actrual button in 15. 
But I think it's the same to build the example of mono_tum as before steps, so I think it's the same as build. 
This location is where you put your parameters into, which corresponding to main's **argv, the location I think it's same to "Right click the mono_tum project and then click Property->Config Property->Debug" in vs2013 as in vs2015.

**Comment by donald2016** [comment]
Thanks. Since I cannot locate where to input the values for Usage, I commented out "if(argc != 4)" and manually input the values for argv to solve the problem. Then everything works fine (just a bit of wait every time I change the source)

**Comment by phdsky** [comment]
Hi, donald2016
As you mentioned the problem -> (just a bit of wait every time I change the source), 
I suggest you to open "incremental compile" option in vs17, you can search google to find that, it will speeds compilation a lot (not compile completely every time you change the source, just the modified part).
